### PR TITLE
Remove dependency on Bower

### PR DESCRIPTION
**Pull request by patocallaghan**
* Replaces colpick Bower package with an npm version
* Removes bower.json and .bowerrc
* Cleans up .travis.yml and removes references to Bower

### CODE REVIEW

**Comment by lukemelia** [comment]
@patocallaghan I just tried to use this from our app and got an error:

```
Error: ENOENT: no such file or directory, open '/Users/lmelia/p/yapp/editor/tmp/source_map_concat-input_base_path-4efWrL8n.tmp/node_modules/jquery-colpick/js/colpick.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at SourceMap.addFile (/Users/lmelia/p/yapp/editor/node_modules/ember-cli/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /Users/lmelia/p/yapp/editor/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/Users/lmelia/p/yapp/editor/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:198:24)
    at /Users/lmelia/p/yapp/editor/node_modules/ember-cli/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/Users/lmelia/p/yapp/editor/node_modules/ember-cli/node_modules/fast-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:567:5)
    at new Promise (/Users/lmelia/p/yapp/editor/node_modules/ember-cli/node_modules/fast-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1039:33)
```

**Comment by patocallaghan** [comment]
@lukemelia that's really strange as I'm using my branch in our app currently 🤔 `node_modules/jquery-colpick/js/colpick.js` is on disk?

**Comment by lukemelia** [comment]
Yep @patocallaghan:

```
➜  editor git:(feature/recent-docs) ✗ ls -al node_modules/jquery-colpick/js/colpick.js
-rw-r--r--  1 lmelia  staff  29632 May 27  2015 node_modules/jquery-colpick/js/colpick.js
```

**Comment by patocallaghan** [comment]
@lukemelia feel free to revert this change if you aren't happy with it.

It would be great to get a reproduction of it though. I'm currently spinning up a new app and installing it. What version of ember-cli/sourcemaps does your app use?

**Comment by lukemelia** [comment]
It would be great to get to the bottom of it. I am on:

    "ember-cli": "2.12.0",
    "ember-source": "~2.12.0"

**Comment by patocallaghan** [comment]
Thanks @lukemelia I have a meeting to run to now but I'll follow up afterwards

**Comment by patocallaghan** [comment]
@lukemelia so the issue is that all versions of ember-cli < 2.15.0 won't work with these changes. Use `app.import` to import assets from `node_modules` was only introduced in ember-cli 2.15.0 https://www.emberjs.com/blog/2017/09/01/ember-2-15-released.html#toc_app-import-files-within-node_modules

I've confirmed this by creating apps with 2.14.2 and below and it generates the errors you are seeing. Apps I've generated using from 2.15.0 work fine.

This will constitute a breaking change so people on older ember-cli's won't be affected.

**Comment by lukemelia** [comment]
Good sleuthing @patocallaghan! I'm OK with releasing this as 1.0.0 with a requirement for ember-cli >= 2.15. I think we should have a helpful error message though. Is that something you would be up for PRing?

**Comment by patocallaghan** [comment]
Yep sure, I’ll do that. Not exactly certain how to grab the ember-cli version but I’ll have a dig around. How does the following sound as an error “Ember-colpick > 1.0.0 is only supported in ember-cli >= 2.15.0. To fix either downgrade ember-colpick or upgrade ember-cli.”

**Comment by lukemelia** [comment]
Perfect 👍 I think ember-cli-dependency-checker might be helpful for this.

**Pull request merged**
